<?php

return array(
    'key' => 'group_dynamic-content',
    'title' => 'Dynamischer Inhalt',
    'fields' => array(
        array(
            'key' => 'field_6855386f314eb',
            'label' => 'Dynamischer Inhalt',
            'name' => 'dynamic_content',
            'aria-label' => '',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_flexible_advanced' => 1,
            'acfe_flexible_stylised_button' => 1,
            'acfe_flexible_layouts_templates' => 1,
            'acfe_flexible_layouts_previews' => 0,
            'acfe_flexible_layouts_placeholder' => 1,
            'acfe_flexible_layouts_thumbnails' => 1,
            'acfe_flexible_layouts_settings' => 1,
            'acfe_flexible_async' => array(),
            'acfe_flexible_add_actions' => array(),
            'acfe_flexible_remove_button' => array(),
            'acfe_flexible_modal_edit' => array(
                'acfe_flexible_modal_edit_enabled' => '1',
                'acfe_flexible_modal_edit_size' => 'large',
            ),
            'acfe_flexible_modal' => array(
                'acfe_flexible_modal_enabled' => '1',
                'acfe_flexible_modal_title' => '',
                'acfe_flexible_modal_size' => 'full',
                'acfe_flexible_modal_col' => '4',
                'acfe_flexible_modal_categories' => '0',
            ),
            'layouts' => array(
                'layout_685538b309feb' => array(
                    'key' => 'layout_685538b309feb',
                    'name' => '',
                    'label' => '',
                    'display' => 'block',
                    'sub_fields' => array(),
                    'min' => '',
                    'max' => '',
                    'acfe_flexible_render_template' => '',
                    'acfe_flexible_render_style' => '',
                    'acfe_flexible_render_script' => '',
                    'acfe_flexible_thumbnail' => '',
                    'acfe_flexible_settings' => false,
                    'acfe_flexible_settings_size' => 'medium',
                    'acfe_flexible_modal_edit_size' => false,
                    'acfe_flexible_category' => false,
                ),
            ),
            'min' => '',
            'max' => '',
            'button_label' => 'Eintrag hinzufügen',
            'acfe_flexible_hide_empty_message' => false,
            'acfe_flexible_empty_message' => '',
            'acfe_flexible_layouts_state' => false,
        ),
    ),
    'location' => array(
    ),
    'menu_order' => 1,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'block_editor',
        1 => 'the_content',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => array(
        0 => 'php',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
    'modified' => 1750415770,
);
