<?php

return array(
    'key' => 'group_flexible-content',
    'title' => 'Flexibler Inhalt',
    'fields' => array(
        'main' => array(
            'key' => 'field_flexible_content',
            'name' => 'flexible_content',
            'aria-label' => '',
            'type' => 'flexible_content',
            'instructions' => 'Bitte wählen Sie hier die dynamischen Inhalt aus, die auf dieser Seite erscheinen sollen.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_flexible_advanced' => 1,
            'acfe_flexible_stylised_button' => 1,
            'acfe_flexible_layouts_templates' => 1,
            'acfe_flexible_layouts_previews' => 1,
            'acfe_flexible_layouts_placeholder' => 1,
            'acfe_flexible_layouts_thumbnails' => 1,
            'acfe_flexible_layouts_settings' => 1,
            'acfe_flexible_async' => array(),
            'acfe_flexible_add_actions' => array(),
            'acfe_flexible_remove_button' => array(),
            'acfe_flexible_modal_edit' => array(
                'acfe_flexible_modal_edit_enabled' => '1',
                'acfe_flexible_modal_edit_size' => 'large',
            ),
            'acfe_flexible_modal' => array(
                'acfe_flexible_modal_enabled' => '1',
                'acfe_flexible_modal_title' => '',
                'acfe_flexible_modal_size' => 'full',
                'acfe_flexible_modal_col' => '4',
                'acfe_flexible_modal_categories' => '0',
            ),
            'min' => '',
            'max' => '',
            'button_label' => 'Eintrag hinzufügen',
            'acfe_flexible_hide_empty_message' => false,
            'acfe_flexible_empty_message' => '',
            'acfe_flexible_layouts_state' => false,
        ),
    ),
    'menu_order' => 1,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => [
        'block_editor',
        'the_content',
    ],
    'active' => true,
    'description' => 'Bitte wählen Sie einen dynamischen Inhalt aus, um ihn hinzuzufügen.',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
);
